name: CI

on:
  push:
    branches: [main]
  pull_request: null
  workflow_dispatch: null

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run -- pytest tests
